### ISSUE TITLE
[FEATURE] - [RADAR]

### ISSUE THREAD

**Issue by Kirattus** [lucasmonstrox/tibiapi#9]
Hi!
In feature there is something to be done about the location of the map.
Any chance of releasing this feature before the others?

**Comment by lucasmonstrox** [comment]
Finished today https://github.com/lucasmonstrox/tibiapi/pull/10 to get floor level. I will implement tomorrow strategies to get full coordinate.

**Comment by lucasmonstrox** [comment]
@Kirattus added way to get coordinate here in PR https://github.com/lucasmonstrox/tibiapi/pull/11

The order of algorithms to get coordinate is:

1. comparing current radar image hash from previous one, it means, hashes are the same. It will avoid computation when character is stopped. It will respond in `3 microseconds`.
2. hashing radar image and getting it from a `Dict` with key/pairs of all hash:coordinate. It will respond in `6 microseconds`.
3. locating from small area based on previous coordinate if it is present. I can improve it in near future, reducing the size of small area. But I need to make some tests because I'm not sure if is 100% safe. Also, I can try with hash displacement for each direction after character move.
4. locating in the whole floor level image in first locating or before teleport. It will respond in `300 milliseconds`.

**Comment by lucasmonstrox** [comment]
@Kirattus already done!
